export type PANEL_OPEN = 'PANEL_OPEN';
export const PANEL_OPEN: PANEL_OPEN = 'PANEL_OPEN';

export type PANEL_CLOSE = 'PANEL_CLOSE';
export const PANEL_CLOSE: PANEL_CLOSE = 'PANEL_CLOSE';

export type PANEL_EXECUTE_COMMAND = 'PANEL_EXECUTE_COMMAND';
export const PANEL_EXECUTE_COMMAND: PANEL_EXECUTE_COMMAND = 'PANEL_EXECUTE_COMMAND';

export type PANEL_UP = 'PANEL_UP';
export const PANEL_UP: PANEL_UP = 'PANEL_UP';

export type PANEL_DOWN = 'PANEL_DOWN';
export const PANEL_DOWN: PANEL_DOWN = 'PANEL_DOWN';

export type PANEL_KEYPRESS = 'PANEL_KEYPRESS';
export const PANEL_KEYPRESS: PANEL_KEYPRESS = 'PANEL_KEYPRESS';

export type SEARCH_CHANGE = 'SEARCH_CHANGE';
export const SEARCH_CHANGE: SEARCH_CHANGE = 'SEARCH_CHANGE';

export type GET_FAVORITES = 'GET_FAVORITES';
export const GET_FAVORITES: GET_FAVORITES = 'GET_FAVORITES';

export type SHOW_FAVORITES = 'SHOW_FAVORITES';
export const SHOW_FAVORITES: SHOW_FAVORITES = 'SHOW_FAVORITES';
