export { addToBookmarks } from './AddToBookmarks';
export { addToBookmarksAs } from './AddToBookmarksAs';
export { closeCurrentTab } from './CloseCurrentTab';
export { openNewTab } from './OpenNewTab';
export { showBookmarks } from './ShowBookmarks';
export { showDownloads } from './ShowDownloads';
export { showExtensions } from './ShowExtensions';
export { showHistory } from './ShowHistory';
export { showSettings } from './ShowSettings';
